# Generated by Django 4.2.5 on 2023-09-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackerId', models.CharField(max_length=10)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('isFixed', models.FloatField(default=0.0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(default=0.0)),
                ('bearing', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('battery_level', models.FloatField(default=0.0)),
                ('immobilisation_switch_state', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
