# Generated by Django 4.2.5 on 2023-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_myvehicle_owner_remove_myvehicle_trackerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immobilisation_switch_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='myvehicle',
            name='immobilisation_switch_state',
        ),
    ]
